version: '3'
services:
  web:
    build: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=posTgress23
      - POSTGRES_DB=rsoi_persons
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=posTgress23
      - POSTGRES_DB=rsoi_persons
