name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]

    services: 
       postgres: 
         image: postgres:latest 
         env: 
           POSTGRES_USER: postgres 
           POSTGRES_PASSWORD: posTgress23
  
         ports: 
           - 5432:5432 
    
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      
      - name: install psql 
        run: | 
          apt update -y 
          apt install -y postgresql postgresql-contrib 
  
      - name: migrate_database 
        run: | 
          cd scripts_DataBase
          psql -h postgres "sslmode=disable user=postgres port=5432 password=posTgress23" < createDatabase.sql 
          psql -h postgres "sslmode=disable dbname=rsoi_persons_test user=postgres port=5432 password=posTgress23" < createTable.sql 
          psql -h postgres "sslmode=disable dbname=rsoi_persons_test user=postgres port=5432 password=posTgress23" < fillTable.sql
      
      - name: Run tests
        run: |
          pip install coverage
          coverage run classes/uniTests/tests.py
      - name: Tests report
        run: coverage report  
